name: Build & publish kubectl‑curl image

on:
  push:
    branches: [main]               # ← triggers on every push to main
  workflow_dispatch:               # manual trigger
  schedule:
    - cron: '0 6 * * *'            # daily at 06:00 UTC

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Discover the latest stable kubectl release tag (e.g. v1.30.1)
      - name: Get latest kubectl version
        id: kv
        run: |
          ver=$(curl -fsSL https://dl.k8s.io/release/stable.txt)
          echo "kubectl_version=$ver" >> "$GITHUB_OUTPUT"

      # 2. Abort early if that tag is not yet published
      - name: Verify download URL
        run: |
          url="https://dl.k8s.io/release/${{ steps.kv.outputs.kubectl_version }}/bin/linux/amd64/kubectl"
          curl -fIs "$url" >/dev/null

      # 3. Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Build & push (immutable tag + rolling latest)
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kubectl-curl:${{ steps.kv.outputs.kubectl_version }}
            ghcr.io/${{ github.repository_owner }}/kubectl-curl:latest
          build-args: |
            KUBECTL_VERSION=${{ steps.kv.outputs.kubectl_version }}

      # 5. Sanity‑check the resulting image
      - name: Verify kubectl version inside the image
        run: |
          docker run --rm ghcr.io/${{ github.repository_owner }}/kubectl-curl:${{ steps.kv.outputs.kubectl_version }} \
            kubectl version --client --short
